//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T5_Ejercicio1.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("T5_Ejercicio1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ball {
            get {
                object obj = ResourceManager.GetObject("ball", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡No hay nada seleccionado para mover!.
        /// </summary>
        internal static string ERR_CANTMOVE_MSG {
            get {
                return ResourceManager.GetString("ERR_CANTMOVE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Oh no!.
        /// </summary>
        internal static string ERR_CANTMOVE_TITLE {
            get {
                return ResourceManager.GetString("ERR_CANTMOVE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡No hay nada seleccionado para borrar!.
        /// </summary>
        internal static string ERR_NOSELECTION_MSG {
            get {
                return ResourceManager.GetString("ERR_NOSELECTION_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Ups!.
        /// </summary>
        internal static string ERR_NOSELECTION_TITLE {
            get {
                return ResourceManager.GetString("ERR_NOSELECTION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡No hay texto que añadir a la lista!.
        /// </summary>
        internal static string ERR_NOTEXT_MSG {
            get {
                return ResourceManager.GetString("ERR_NOTEXT_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Ojo!.
        /// </summary>
        internal static string ERR_NOTEXT_TITLE {
            get {
                return ResourceManager.GetString("ERR_NOTEXT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        internal static System.Drawing.Icon icon1 {
            get {
                object obj = ResourceManager.GetObject("icon1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        internal static System.Drawing.Icon icon2 {
            get {
                object obj = ResourceManager.GetObject("icon2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        internal static System.Drawing.Icon icon3 {
            get {
                object obj = ResourceManager.GetObject("icon3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Índices seleccionados: .
        /// </summary>
        internal static string LBINDEX_MSG {
            get {
                return ResourceManager.GetString("LBINDEX_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ninguno.
        /// </summary>
        internal static string LBINDEX_NONE {
            get {
                return ResourceManager.GetString("LBINDEX_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elementos en lista principal: {0}.
        /// </summary>
        internal static string LBTOTAL_MSG {
            get {
                return ResourceManager.GetString("LBTOTAL_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Mira como me muevo!.
        /// </summary>
        internal static string MAIN_TITLE {
            get {
                return ResourceManager.GetString("MAIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista secundaria, tamaño {0}.
        /// </summary>
        internal static string TOOLTIP_LBOXB {
            get {
                return ResourceManager.GetString("TOOLTIP_LBOXB", resourceCulture);
            }
        }
    }
}
