//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T5_Ejercicio3.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("T5_Ejercicio3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir del programa.
        /// </summary>
        internal static string CLOSE_CONFIRM_TITLE {
            get {
                return ResourceManager.GetString("CLOSE_CONFIRM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de que desea salir del programa?.
        /// </summary>
        internal static string CLOSE_CONFIRM_TXT {
            get {
                return ResourceManager.GetString("CLOSE_CONFIRM_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Ups!.
        /// </summary>
        internal static string ERR_BADFILE_TITLE {
            get {
                return ResourceManager.GetString("ERR_BADFILE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha podido abrir la imagen. Prueba con otra.
        /// </summary>
        internal static string ERR_BADFILE_TXT {
            get {
                return ResourceManager.GetString("ERR_BADFILE_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Vaya!.
        /// </summary>
        internal static string ERR_OPENING_TITLE {
            get {
                return ResourceManager.GetString("ERR_OPENING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha podido abrir la imagen.
        ///Información del error: {0}.
        /// </summary>
        internal static string ERR_OPENING_TXT {
            get {
                return ResourceManager.GetString("ERR_OPENING_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre: {0}
        ///Tamaño: {1} {2}
        ///Resolución: {3}x{4}px.
        /// </summary>
        internal static string LB_INFO {
            get {
                return ResourceManager.GetString("LB_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivos de imagen (*.jpg, *.jpeg, *.jpe, *.jfif, *.png *.bmp) | *.jpg; *.jpeg; *.jpe; *.jfif; *.png *.bmp.
        /// </summary>
        internal static string OPENDIALOG_FILTERS {
            get {
                return ResourceManager.GetString("OPENDIALOG_FILTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abrir imagen.
        /// </summary>
        internal static string OPENDIALOG_TITLE {
            get {
                return ResourceManager.GetString("OPENDIALOG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visor de imagenes -&lt;{0}&gt;.
        /// </summary>
        internal static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visor de imagenes.
        /// </summary>
        internal static string TITLE_EMPTY {
            get {
                return ResourceManager.GetString("TITLE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anterior imagen.
        /// </summary>
        internal static string TOOLTIP_LEFT {
            get {
                return ResourceManager.GetString("TOOLTIP_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente imagen.
        /// </summary>
        internal static string TOOLTIP_RIGHT {
            get {
                return ResourceManager.GetString("TOOLTIP_RIGHT", resourceCulture);
            }
        }
    }
}
